#pragma once

#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE

// #define TAPPING_TERM 150
#define TAPPING_TERM 250

// #define FLOW_TAP_TERM 150
#define RETRO_TAPPING
#define PERMISSIVE_HOLD

#define COMBO_TERM 25

