#pragma once

#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE
#define FORCE_NKRO

#define TAPPING_TERM 200

#define COMBO_TERM 25

#define ENCODER_A_PINS { GP0, GP2 }
#define ENCODER_B_PINS { GP1, GP3 }
#define ENCODER_MAP_KEY_DELAY 15
#define ENCODER_DIRECTION_FLIP
#define ENCODER_RESOLUTIONS { 4, 4 }
